apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.dataset.pvcName }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "product-similarity-service.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.dataset.storage }}
