apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.dataset.pvcName }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "product-similarity-service.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.dataset.accessMode }}
  {{- if .Values.dataset.storageClass }}
  storageClassName: {{ .Values.dataset.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.dataset.storage }}
